name: Build-Test-Release

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install
        run: npm ci || npm install
      - name: Build
        run: npm run build
      - name: Package artifact
        run: |
          set -euxo pipefail
          if [ -d dist ]; then zip -r build.zip dist; else zip -r build.zip .; fi
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build.zip
          if-no-files-found: error

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: .
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Unpack artifact
        run: unzip -l build.zip || true
      - name: Run Automated Tests
        run: |
          set -euxo pipefail
          npm test --if-present
          echo "All tests passed"

  release:
    name: Release (dev)
    runs-on: ubuntu-latest
    needs: test
    environment: dev
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: .
      - name: Release to Dev
        uses: softprops/action-gh-release@v2
        with:
          tag_name: dev-${{ github.run_number }}
          prerelease: true
          body: "Automated dev release after successful tests"
          files: build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
